name: Affected Apps

on:
  push:
    branches:
      - main

jobs:
  main:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    env:
        AFFECTED_APPS: ''

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Set NX shas
        uses: nrwl/nx-set-shas@v3

      - name: Install dependencies
        run: npm ci

      - name: Determine App to Deploy
        id: appcheck
        run: |
            output=$(npx nx affected -t build)
            projects="(app1|app2)"
            modified_apps=($(echo $output | grep -o -E "$projects" | sort | uniq))
            IFS=','  # Definindo o separador interno como vírgula
            printf -v modified_apps "%s" "${modified_apps[*]}"
            echo "AFFECTED_APPS=${modified_apps}" >> $GITHUB_ENV
            if [ -z "$modified_apps" ]; then
              echo "Nenhum app afetado, finalizando..."
              exit 0
            fi
      - name: Print Affected Apps
        run: |
         echo "Affected Apps: ${{ env.AFFECTED_APPS }}"

      - name: Run linting
        run: npx nx affected -t lint --parallel=3

      - name: Run tests
        run: npx nx affected -t test --parallel=3 --configuration=ci

      - name: Build
        run: npx nx affected -t build --parallel=3 --configuration=ci

      - name: Deploy App01
        if: contains(env.AFFECTED_APPS, 'app1')
        id: deployApp1
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_GRASS_05828B01E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: 'upload'
          app_location: '/dist/apps/app1'
          output_location: ''

      - name: Deploy App02
        if: contains(env.AFFECTED_APPS, 'app2')
        id: deployApp2
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_ROCK_0061A3810 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: 'upload'
          app_location: '/dist/apps/app2'
          output_location: ''

