name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
    paths:
      - apps/app2
      - .github/workflows/app02.yml
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - apps/app2
      - .github/workflows/app02.yml
jobs:
  main:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Set NX shas
        uses: nrwl/nx-set-shas@v3

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npx nx affected -t lint --parallel=3

      - name: Run tests
        run: npx nx affected -t test --parallel=3 --configuration=ci

      - name: Build
        run: npx nx affected -t build --parallel=3 --configuration=ci

      - name: Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_ROCK_0061A3810 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: 'upload'
          app_location: '/dist/apps/app2'
          output_location: ''
